# Auto-generated by update-deps.sh - DO NOT EDIT MANUALLY
# Source: versions.txt
#
# To update: ./update-deps.sh
#
{ fetchFromGitHub, fetchurl, lib }:

{
  args = fetchFromGitHub {
    owner = "Taywee";
    repo = "args";
    rev = "6.4.6";
    hash = "sha256-2gH3h3QAl0+XVULt/fR2UUGKNIxTUmnRRdxPOFdpVy4=";
  };

  lz4 = fetchFromGitHub {
    owner = "lz4";
    repo = "lz4";
    rev = "v1.10.0";
    hash = "sha256-/dG1n59SKBaEBg72pAWltAtVmJ2cXxlFFhP+klrkTos=";
  };

  libuv = fetchFromGitHub {
    owner = "libuv";
    repo = "libuv";
    rev = "v1.48.0";
    hash = "sha256-U68BmIQNpmIy3prS7LkYl+wvDJQNikoeFiKh50yQFoA=";
  };

  glm = fetchFromGitHub {
    owner = "g-truc";
    repo = "glm";
    rev = "1.0.1";
    hash = "sha256-GnGyzNRpzuguc3yYbEFtYLvG+KiCtRAktiN+NvbOICE=";
  };

  stb = fetchFromGitHub {
    owner = "nothings";
    repo = "stb";
    rev = "f75e8d1cad7d90d72ef7a4661f1b994ef78b4e31";
    hash = "sha256-koprbFMmNrqpGZmL9d6yRFLUtbSFtGSKNxxadABFYuQ=";
  };

  yaml-cpp = fetchFromGitHub {
    owner = "jbeder";
    repo = "yaml-cpp";
    rev = "0.8.0";
    hash = "sha256-J87oS6Az1/vNdyXu3L7KmUGWzU0IAkGrGMUUha+xDXI=";
  };

  spdlog = fetchFromGitHub {
    owner = "gabime";
    repo = "spdlog";
    rev = "v1.16.0";
    hash = "sha256-VB82cNfpJlamUjrQFYElcy0CXAbkPqZkD5zhuLeHLzs=";
  };

  ytrace = fetchFromGitHub {
    owner = "zokrezyl";
    repo = "ytrace";
    rev = "da73e1fba172c61d204debd84f30f4703c6f3d19";
    hash = "sha256-ObO0vr4MLCyUvRJdvhZ7a8xCxdrA5JpjhrnQfF2VIiI=";
  };

  msgpack-cxx = fetchFromGitHub {
    owner = "msgpack";
    repo = "msgpack-c";
    rev = "cpp-7.0.0";
    hash = "sha256-kg4mpNiigfZ59ZeL8LXEHwtkLU8Po+vgRcUcgTJd+h4=";
  };

  zlib = fetchFromGitHub {
    owner = "madler";
    repo = "zlib";
    rev = "v1.3.1";
    hash = "sha256-TkPLWSN5QcPlL9D0kc/yhH0/puE9bFND24aj5NVDKYs=";
  };

  libpng = fetchFromGitHub {
    owner = "pnggroup";
    repo = "libpng";
    rev = "v1.6.43";
    hash = "sha256-Mo1M8TuVaoSIb7Hy2u6zgjZ1DKgpmgNmGRP6dGg/aTs=";
  };

  msdfgen = fetchFromGitHub {
    owner = "Chlumsky";
    repo = "msdfgen";
    rev = "v1.12";
    hash = "sha256-QLzfZP9Xsc5HBvF+riamqVY0pYN5umyEsiJV7W8JNyI=";
  };

  brotli = fetchFromGitHub {
    owner = "google";
    repo = "brotli";
    rev = "v1.1.0";
    hash = "sha256-MvceRcle2dSkkucC2PlsCizsIf8iv95d8Xjqew266wc=";
  };

  bzip2 = fetchFromGitHub {
    owner = "libarchive";
    repo = "bzip2";
    rev = "bzip2-1.0.8";
    hash = "sha256-aPUjQUuKF3pvvWhfFuoW3FhYhsUv4RkxatYpmgX6/EE=";
  };

  freetype = fetchFromGitHub {
    owner = "freetype";
    repo = "freetype";
    rev = "VER-2-13-2";
    hash = "sha256-Io9k8xmOKrk+4GSi3PUU60X68T4BpG8dru1/KO+jVRk=";
  };

  glfw = fetchFromGitHub {
    owner = "glfw";
    repo = "glfw";
    rev = "3.4";
    hash = "sha256-FcnQPDeNHgov1Z07gjFze0VMz2diOrpbKZCsI96ngz0=";
  };

  glfw3webgpu = fetchFromGitHub {
    owner = "eliemichel";
    repo = "glfw3webgpu";
    rev = "8f14534e79c590e8a7f7795ea42e01bedea9e137";
    hash = "sha256-PYgjk6bFeUhH796vQRUINN5mpafRviZN+AemHuP7wtI=";
  };

  incbin = fetchFromGitHub {
    owner = "graphitemaster";
    repo = "incbin";
    rev = "main";
    hash = "sha256-vgOfViZnWTKpBB6vDNDJSB3YuuGGVhg++zsi9Ubatno=";
  };

  libjpeg-turbo = fetchFromGitHub {
    owner = "libjpeg-turbo";
    repo = "libjpeg-turbo";
    rev = "3.1.3";
    hash = "sha256-jcdoCJlsDEr87i5MN4I6zARZVUxQfzdM0Ltg3IyrNRg=";
  };

  thorvg = fetchFromGitHub {
    owner = "thorvg";
    repo = "thorvg";
    rev = "v1.0.1";
    hash = "sha256-3UtZvGAz1BUSBXY5ZhnueMohIvzFcZ6MO8crVhR0ppI=";
  };

  imgui = fetchFromGitHub {
    owner = "ocornut";
    repo = "imgui";
    rev = "v1.92.5";
    hash = "sha256-9A+qRsrsFxLAeDeV60qFTiBmg2XBKgERAxKZgD8AwTM=";
  };

  tinyxml2 = fetchFromGitHub {
    owner = "leethomason";
    repo = "tinyxml2";
    rev = "10.0.0";
    hash = "sha256-9xrpPFMxkAecg3hMHzzThuy0iDt970Iqhxs57Od+g2g=";
  };

  cpr = fetchFromGitHub {
    owner = "libcpr";
    repo = "cpr";
    rev = "1.14.1";
    hash = "sha256-kwbkdAeTpkEJbzvqpUQx007ZIBtwqOPG8n41TvFxeiM=";
  };

  # curl is a dependency of cpr, fetched via FetchContent
  curl = fetchurl {
    url = "https://github.com/curl/curl/releases/download/curl-8_13_0/curl-8.13.0.tar.xz";
    hash = "sha256-Sgk5eaPC0C3i+8AFSaMncQB/LngDLG+qXs0vep4VICU=";
  };

  pdfio = fetchFromGitHub {
    owner = "michaelrsweet";
    repo = "pdfio";
    rev = "v1.4.0";
    hash = "sha256-o+1aTCNJMzu33RjDZmhe9TIT3qQSM0zoei9pMNjNOkM=";
  };

  litehtml = fetchFromGitHub {
    owner = "litehtml";
    repo = "litehtml";
    rev = "v0.9";
    hash = "sha256-ZE/HKzo3ejKpW/ih3sJwn2hzCtsBhAXeJWGezYd6Yc4=";
  };

  tree-sitter = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter";
    rev = "v0.26.5";
    hash = "sha256-tnZ8VllRRYPL8UhNmrda7IjKSeFmmOnW/2/VqgJFLgU=";
  };

  tree-sitter-c = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-c";
    rev = "v0.24.1";
    hash = "sha256-gmzbdwvrKSo6C1fqTJFGxy8x0+T+vUTswm7F5sojzKc=";
  };

  tree-sitter-cpp = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-cpp";
    rev = "v0.23.4";
    hash = "sha256-tP5Tu747V8QMCEBYwOEmMQUm8OjojpJdlRmjcJTbe2k=";
  };

  tree-sitter-python = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-python";
    rev = "v0.25.0";
    hash = "sha256-F5XH21PjPpbwYylgKdwD3MZ5o0amDt4xf/e5UikPcxY=";
  };

  tree-sitter-javascript = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-javascript";
    rev = "v0.25.0";
    hash = "sha256-2Jj/SUG+k8lHlGSuPZvHjJojvQFgDiZHZzH8xLu7suE=";
  };

  tree-sitter-typescript = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-typescript";
    rev = "v0.23.2";
    hash = "sha256-CU55+YoFJb6zWbJnbd38B7iEGkhukSVpBN7sli6GkGY=";
  };

  tree-sitter-rust = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-rust";
    rev = "v0.24.0";
    hash = "sha256-y3sJURlSTM7LRRN5WGIAeslsdRZU522Tfcu6dnXH/XQ=";
  };

  tree-sitter-go = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-go";
    rev = "v0.25.0";
    hash = "sha256-y7bTET8ypPczPnMVlCaiZuswcA7vFrDOc2jlbfVk5Sk=";
  };

  tree-sitter-java = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-java";
    rev = "v0.23.5";
    hash = "sha256-OvEO1BLZLjP3jt4gar18kiXderksFKO0WFXDQqGLRIY=";
  };

  tree-sitter-bash = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-bash";
    rev = "v0.25.1";
    hash = "sha256-ONQ1Ljk3aRWjElSWD2crCFZraZoRj3b3/VELz1789GE=";
  };

  tree-sitter-json = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-json";
    rev = "v0.24.8";
    hash = "sha256-DNZC2cTy1C8OaMOpEHM6NoRtOIbLaBf0CLXXWCKODlw=";
  };

  tree-sitter-yaml = fetchFromGitHub {
    owner = "tree-sitter-grammars";
    repo = "tree-sitter-yaml";
    rev = "v0.7.2";
    hash = "sha256-BX6TOfAZLW+0h2TNsgsLC9K2lfirraCWlBN2vCKiXQ4=";
  };

  tree-sitter-toml = fetchFromGitHub {
    owner = "tree-sitter-grammars";
    repo = "tree-sitter-toml";
    rev = "v0.7.0";
    hash = "sha256-m9RlGkHiOL/PNENrdEPqtPlahSqGymsx7gZrCoN/Lsk=";
  };

  tree-sitter-html = fetchFromGitHub {
    owner = "tree-sitter";
    repo = "tree-sitter-html";
    rev = "v0.23.2";
    hash = "sha256-Pd5Me1twLGOrRB3pSMVX9M8VKenTK0896aoLznjNkGo=";
  };

  tree-sitter-xml = fetchFromGitHub {
    owner = "tree-sitter-grammars";
    repo = "tree-sitter-xml";
    rev = "v0.7.0";
    hash = "sha256-/0IQsTkvFQOWnkLc2srjg2bn1sB1sNA6Sm3nwKGUDj4=";
  };

  howerj_cdb = fetchFromGitHub {
    owner = "howerj";
    repo = "cdb";
    rev = "v4.3.2";
    hash = "sha256-8SrqoarYCPNiP7nxngmFnVKZgmPnL0KafS+OhP+4s2I=";
  };

  cdb = fetchurl {
    url = "https://cdb.cr.yp.to/cdb-20251021.tar.gz";
    hash = "sha256-jlMdY5C818mky9Fv7TYybu546LDlwHg6gVimp5Q3490=";
  };

  libmagic = fetchurl {
    url = "https://astron.com/pub/file/file-5.45.tar.gz";
    hash = "sha256-/Jf1ECm7DiyfTjv/79r2ePDgOe6HK53lwAKm0Jx4TYI=";
  };

  dawn-linux = fetchurl {
    url = "https://github.com/google/dawn/releases/download/v20260214.164635/Dawn-1a3afc99a7ef7dacaab73b71d44575c4f1bf2dd7-ubuntu-latest-Release.tar.gz";
    hash = "sha256-m+4KJaRF+KZJy+veMFvbTJOhybbk+J9r8y1/BUqH7q8=";
  };

  dawn-macos-arm64 = fetchurl {
    url = "https://github.com/google/dawn/releases/download/v20260214.164635/Dawn-1a3afc99a7ef7dacaab73b71d44575c4f1bf2dd7-macos-latest-Release.tar.gz";
    hash = "sha256-U2x66eLmeSJHl4gK/mo6a6By5phtW8m3zOGMLXMKpXg=";
  };

  dawn-macos-x86_64 = fetchurl {
    url = "https://github.com/google/dawn/releases/download/v20260214.164635/Dawn-1a3afc99a7ef7dacaab73b71d44575c4f1bf2dd7-macos-15-intel-Release.tar.gz";
    hash = "sha256-oHBNDtONTLPuXOYa7t4QDG1fpXysDjdlGNf832Kg2wo=";
  };

  # Video codecs (new deps)
  dav1d = fetchurl {
    url = "https://code.videolan.org/videolan/dav1d/-/archive/1.5.0/dav1d-1.5.0.tar.gz";
    hash = "sha256-eLFdmVS1E+qS0n85NiU13tIkPhsJJP3jnzejHr7V92s=";
  };

  openh264 = fetchFromGitHub {
    owner = "cisco";
    repo = "openh264";
    rev = "v2.4.1";
    hash = "sha256-ai7lcGcQQqpsLGSwHkSs7YAoEfGCIbxdClO6JpGA+MI=";
  };

  minimp4 = fetchFromGitHub {
    owner = "lieff";
    repo = "minimp4";
    rev = "4575afb4f69ace25a1a048e25cc86bf8c8d14f2b";
    hash = "sha256-VGsUUfAdeW3qzP4WK2lxMPsRT8qzHTL99I3UwaiwW54=";
  };

}
