#!/usr/bin/env bash
#
# Automatically updates cpm-sources.nix based on versions.txt
# This script computes SRI hashes and generates the Nix expression.
#
# Usage: ./update-deps.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$SCRIPT_DIR/versions.txt"
OUTPUT_FILE="$SCRIPT_DIR/cpm-sources.nix"

# Temporary file for building output
TMP_FILE=$(mktemp)
trap "rm -f $TMP_FILE" EXIT

# Check for required tools
for cmd in nix-prefetch-url nix; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "Error: $cmd is required but not found"
        exit 1
    fi
done

echo "=== Updating Nix dependencies from versions.txt ==="
echo ""

# Start generating the Nix file
cat > "$TMP_FILE" << 'HEADER'
# Auto-generated by update-deps.sh - DO NOT EDIT MANUALLY
# Source: versions.txt
#
# To update: ./update-deps.sh
#
{ fetchFromGitHub, fetchurl, lib }:

{
HEADER

# Function to compute hash for GitHub repo
compute_github_hash() {
    local owner_repo="$1"
    local rev="$2"
    local owner="${owner_repo%/*}"
    local repo="${owner_repo#*/}"

    local url="https://github.com/${owner}/${repo}/archive/${rev}.tar.gz"

    # Fetch and compute hash (--unpack for archives)
    local hash
    if ! hash=$(nix-prefetch-url --unpack "$url" 2>/dev/null); then
        echo "FETCH_FAILED"
        return 1
    fi

    if [[ -z "$hash" ]]; then
        echo "FETCH_FAILED"
        return 1
    fi

    # Convert to SRI format
    nix hash convert --hash-algo sha256 --to sri "$hash" 2>/dev/null || \
    nix hash to-sri --type sha256 "$hash" 2>/dev/null
}

# Function to compute hash for URL
compute_url_hash() {
    local url="$1"
    local unpack="${2:-true}"

    local hash
    if [[ "$unpack" == "true" ]]; then
        if ! hash=$(nix-prefetch-url --unpack "$url" 2>/dev/null); then
            echo "FETCH_FAILED"
            return 1
        fi
    else
        if ! hash=$(nix-prefetch-url "$url" 2>/dev/null); then
            echo "FETCH_FAILED"
            return 1
        fi
    fi

    if [[ -z "$hash" ]]; then
        echo "FETCH_FAILED"
        return 1
    fi

    # Convert to SRI format
    nix hash convert --hash-algo sha256 --to sri "$hash" 2>/dev/null || \
    nix hash to-sri --type sha256 "$hash" 2>/dev/null
}

FAILED_DEPS=()

# Process each line in versions.txt
while IFS='|' read -r name type source version || [[ -n "$name" ]]; do
    # Skip comments and empty lines
    [[ -z "$name" || "$name" =~ ^[[:space:]]*# ]] && continue

    # Trim whitespace
    name=$(echo "$name" | xargs)
    type=$(echo "$type" | xargs)
    source=$(echo "$source" | xargs)
    version=$(echo "$version" | xargs)

    echo "Processing: $name ($type)"

    case "$type" in
        github)
            owner="${source%/*}"
            repo="${source#*/}"

            echo "  Fetching hash for $owner/$repo @ $version..."
            if hash=$(compute_github_hash "$source" "$version"); then
                if [[ "$hash" != "FETCH_FAILED" && -n "$hash" ]]; then
                    echo "  Hash: $hash"
                    cat >> "$TMP_FILE" << EOF
  $name = fetchFromGitHub {
    owner = "$owner";
    repo = "$repo";
    rev = "$version";
    hash = "$hash";
  };

EOF
                else
                    echo "  ERROR: Failed to fetch, skipping"
                    FAILED_DEPS+=("$name")
                fi
            else
                echo "  ERROR: Failed to fetch, skipping"
                FAILED_DEPS+=("$name")
            fi
            ;;

        url)
            url="$source"
            echo "  Fetching hash for $url..."

            # fetchurl doesn't unpack, so compute hash without --unpack
            hash=$(compute_url_hash "$url" "false") || hash="FETCH_FAILED"

            if [[ "$hash" != "FETCH_FAILED" && -n "$hash" ]]; then
                echo "  Hash: $hash"
                cat >> "$TMP_FILE" << EOF
  $name = fetchurl {
    url = "$url";
    hash = "$hash";
  };

EOF
            else
                echo "  ERROR: Failed to fetch, skipping"
                FAILED_DEPS+=("$name")
            fi
            ;;

        *)
            echo "  WARNING: Unknown type '$type', skipping"
            ;;
    esac

done < "$VERSIONS_FILE"

# Close the Nix attrset
echo "}" >> "$TMP_FILE"

# Move to final location
mv "$TMP_FILE" "$OUTPUT_FILE"

echo ""
echo "=== Done ==="
echo "Generated: $OUTPUT_FILE"

if [[ ${#FAILED_DEPS[@]} -gt 0 ]]; then
    echo ""
    echo "WARNING: The following dependencies failed to fetch:"
    for dep in "${FAILED_DEPS[@]}"; do
        echo "  - $dep"
    done
    echo ""
    echo "You may need to update versions.txt with correct URLs/revisions"
fi

echo ""
echo "To verify: nix eval -f $OUTPUT_FILE --apply 'x: builtins.attrNames x'"
