// Auto-generated from ypaint-primitives.yaml — DO NOT EDIT
// Generated by: src/yetty/ypaint/gen-ypaint-types.py
// To regenerate: uv run src/yetty/ypaint/gen-ypaint-types.py

// SDF_* constants are defined in sdf-types.gen.wgsl

fn evaluateYpaintSDF(primOffset: u32, p: vec2<f32>) -> f32 {
    // Layout: [0]=gridOffset, [1]=type, [2]=layer, [3+]=geometry
    // Read grid offset FIRST (u16,u16 packed in u32) and convert to pixel offset
    let gridOffsetPacked = bitcast<u32>(cardStorage[primOffset + 0u]);
    let gridOffsetX = f32(gridOffsetPacked & 0xFFFFu);
    let gridOffsetY = f32(gridOffsetPacked >> 16u);
    let pixelOffset = vec2<f32>(gridOffsetX * grid.cellSize.x, gridOffsetY * grid.cellSize.y);
    let pAdj = p - pixelOffset;

    let primType = bitcast<u32>(cardStorage[primOffset + 1u]);

    switch (primType) {
        case SDF_CIRCLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let radius = cardStorage[primOffset + 5u];
            return sdCircle(pAdj, center, radius);
        }
        case SDF_BOX: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let halfSize = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let round = cardStorage[primOffset + 10u];
            return sdBox(pAdj, center, halfSize, round);
        }
        case SDF_SEGMENT: {
            let p0 = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let p1 = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdSegment(pAdj, p0, p1);
        }
        case SDF_TRIANGLE: {
            let v0 = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let v1 = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let v2 = vec2<f32>(cardStorage[primOffset + 7u], cardStorage[primOffset + 8u]);
            return sdTriangle(pAdj, v0, v1, v2);
        }
        case SDF_BEZIER2: {
            let v0 = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let v1 = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let v2 = vec2<f32>(cardStorage[primOffset + 7u], cardStorage[primOffset + 8u]);
            return sdBezier2(pAdj, v0, v1, v2);
        }
        case SDF_BEZIER3: {
            let v0 = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let v1 = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let v2 = vec2<f32>(cardStorage[primOffset + 7u], cardStorage[primOffset + 8u]);
            let v3 = vec2<f32>(cardStorage[primOffset + 9u], cardStorage[primOffset + 10u]);
            return sdBezier3(pAdj, v0, v1, v2, v3);
        }
        case SDF_ELLIPSE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let radii = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdEllipse(pAdj, center, radii);
        }
        case SDF_ARC: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let sc = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let ra = cardStorage[primOffset + 7u];
            let rb = cardStorage[primOffset + 8u];
            return sdArc(pAdj, center, sc, ra, rb);
        }
        case SDF_ROUNDED_BOX: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let halfSize = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let radii = vec4<f32>(cardStorage[primOffset + 7u], cardStorage[primOffset + 8u], cardStorage[primOffset + 9u], cardStorage[primOffset + 10u]);
            return sdRoundedBox(pAdj, center, halfSize, radii);
        }
        case SDF_RHOMBUS: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let b = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdRhombus(pAdj, center, b);
        }
        case SDF_PENTAGON: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdPentagon(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_HEXAGON: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdHexagon(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_STAR: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdStar(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
        }
        case SDF_PIE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let c = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdPie(pAdj, center, c, cardStorage[primOffset + 7u]);
        }
        case SDF_RING: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let n = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdRing(pAdj, center, n, cardStorage[primOffset + 7u], cardStorage[primOffset + 8u]);
        }
        case SDF_HEART: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdHeart(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_CROSS: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let b = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdCross(pAdj, center, b, cardStorage[primOffset + 7u]);
        }
        case SDF_ROUNDED_X: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdRoundedX(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_CAPSULE: {
            let a = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let b = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdCapsule(pAdj, a, b, cardStorage[primOffset + 7u]);
        }
        case SDF_MOON: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdMoon(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
        }
        case SDF_EGG: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdEgg(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_CHAMFER_BOX: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let halfSize = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdChamferBox(pAdj, center, halfSize, cardStorage[primOffset + 7u]);
        }
        case SDF_ORIENTED_BOX: {
            let a = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let b = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdOrientedBox(pAdj, a, b, cardStorage[primOffset + 7u]);
        }
        case SDF_TRAPEZOID: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdTrapezoid(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
        }
        case SDF_PARALLELOGRAM: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdParallelogram(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
        }
        case SDF_EQUILATERAL_TRIANGLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdEquilateralTriangle(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_ISOSCELES_TRIANGLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let q = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdTriangleIsosceles(pAdj, center, q);
        }
        case SDF_UNEVEN_CAPSULE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdUnevenCapsule(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
        }
        case SDF_OCTOGON: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdOctogon(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_HEXAGRAM: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdHexagram(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_PENTAGRAM: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdPentagram(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_CUT_DISK: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdCutDisk(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_HORSESHOE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let c = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let w = vec2<f32>(cardStorage[primOffset + 8u], cardStorage[primOffset + 9u]);
            return sdHorseshoe(pAdj, center, c, cardStorage[primOffset + 7u], w);
        }
        case SDF_VESICA: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdVesica(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_ORIENTED_VESICA: {
            let a = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let b = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdOrientedVesica(pAdj, a, b, cardStorage[primOffset + 7u]);
        }
        case SDF_ROUNDED_CROSS: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdRoundedCross(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_PARABOLA: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdParabola(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_BLOBBY_CROSS: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdBlobbyCross(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_TUNNEL: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let wh = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdTunnel(pAdj, center, wh);
        }
        case SDF_STAIRS: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let wh = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            return sdStairs(pAdj, center, wh, cardStorage[primOffset + 7u]);
        }
        case SDF_QUADRATIC_CIRCLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdQuadraticCircle(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_HYPERBOLA: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdHyperbola(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_COOL_S: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdCoolS(pAdj, center, cardStorage[primOffset + 5u]);
        }
        case SDF_CIRCLE_WAVE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdCircleWave(pAdj, center, cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
        }
        case SDF_COLOR_WHEEL: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let d = pAdj - center;
            let dist = length(d);
            let ringDist = abs(dist - (cardStorage[primOffset + 6u] + cardStorage[primOffset + 5u]) * 0.5) - (cardStorage[primOffset + 5u] - cardStorage[primOffset + 6u]) * 0.5;
            return ringDist;
        }
        case SDF_LINEAR_GRADIENT_BOX: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let halfSize = vec2<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u]);
            let round = cardStorage[primOffset + 15u];
            return sdBox(pAdj, center, halfSize, round);
        }
        case SDF_LINEAR_GRADIENT_CIRCLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let radius = cardStorage[primOffset + 5u];
            return sdCircle(pAdj, center, radius);
        }
        case SDF_RADIAL_GRADIENT_CIRCLE: {
            let center = vec2<f32>(cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            let radius = cardStorage[primOffset + 5u];
            return sdCircle(pAdj, center, radius);
        }
        case SDF_POLYGON: {
            // Layout: [0]=gridOffset, [1]=type, [2]=layer, [3]=vertexCount, [4-7]=colors, [8+]=vertices
            let vertexCount = bitcast<u32>(cardStorage[primOffset + 3u]);
            let vertexOffset = primOffset + 8u;
            return sdPolygon(pAdj, vertexOffset, vertexCount);
        }
        case SDF_POLYGON_GROUP: {
            // PolygonGroup: [0]=gridOffset, [1]=type, [2]=layer, [3]=vertexCount, [4]=contourCount
            // [5-8]=colors, [9...9+contourCount-1]=contourStarts, [9+contourCount...]=vertices
            // For now, just treat it like a simple polygon (first contour)
            let vertexCount = bitcast<u32>(cardStorage[primOffset + 3u]);
            let contourCount = bitcast<u32>(cardStorage[primOffset + 4u]);
            let vertexOffset = primOffset + 9u + contourCount;
            return sdPolygon(pAdj, vertexOffset, vertexCount);
        }
        default: {
            return 1e10;
        }
    }
}

fn evaluateYpaintSDF3D(primOffset: u32, p: vec3<f32>) -> f32 {
    let primType = bitcast<u32>(cardStorage[primOffset + 0u]);

    switch (primType) {
        case SDF_SPHERE_3D: {
            let pos = vec3<f32>(cardStorage[primOffset + 2u], cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdSphere3D(p - pos, cardStorage[primOffset + 5u]);
        }
        case SDF_BOX_3D: {
            let pos = vec3<f32>(cardStorage[primOffset + 2u], cardStorage[primOffset + 3u], cardStorage[primOffset + 4u]);
            return sdBox3D(p - pos, vec3<f32>(cardStorage[primOffset + 5u], cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]));
        }
        default: { return 1e10; }
    }
}

fn ypaintPrimColors(primOffset: u32) -> vec4<u32> {
    // Layout: [0]=gridOffset, [1]=type, [2]=layer, [3+]=geometry
    let primType = bitcast<u32>(cardStorage[primOffset + 1u]);
    switch (primType) {
        case SDF_CIRCLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_BOX: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_SEGMENT: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_TRIANGLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_BEZIER2: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_BEZIER3: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 12u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ELLIPSE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ARC: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ROUNDED_BOX: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 12u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_RHOMBUS: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_PENTAGON: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_HEXAGON: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_STAR: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_PIE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_RING: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_HEART: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_CROSS: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ROUNDED_X: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_CAPSULE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_MOON: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_EGG: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_CHAMFER_BOX: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ORIENTED_BOX: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_TRAPEZOID: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_PARALLELOGRAM: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_EQUILATERAL_TRIANGLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ISOSCELES_TRIANGLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_UNEVEN_CAPSULE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_OCTOGON: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_HEXAGRAM: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_PENTAGRAM: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_CUT_DISK: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_HORSESHOE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_VESICA: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ORIENTED_VESICA: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ROUNDED_CROSS: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_PARABOLA: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_BLOBBY_CROSS: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_TUNNEL: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_STAIRS: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_QUADRATIC_CIRCLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_HYPERBOLA: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_COOL_S: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_CIRCLE_WAVE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_COLOR_WHEEL: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 12u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_TEXT_GLYPH: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_ROTATED_GLYPH: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 12u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_SPHERE_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_BOX_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_TORUS_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_CYLINDER_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_VERTICAL_CAPSULE_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_CAPPED_CONE_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_OCTAHEDRON_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_PYRAMID_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 7u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_ELLIPSOID_3D: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 8u]),
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 1u]),
                0u);
        }
        case SDF_POLYGON: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 4u]),
                bitcast<u32>(cardStorage[primOffset + 5u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_POLYGON_GROUP: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 5u]),
                bitcast<u32>(cardStorage[primOffset + 6u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                0u);
        }
        case SDF_LINEAR_GRADIENT_BOX: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 13u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                1u);  // flag=1 indicates gradient type
        }
        case SDF_LINEAR_GRADIENT_CIRCLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 10u]),
                bitcast<u32>(cardStorage[primOffset + 12u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                1u);  // flag=1 indicates gradient type
        }
        case SDF_RADIAL_GRADIENT_CIRCLE: {
            return vec4<u32>(
                bitcast<u32>(cardStorage[primOffset + 9u]),
                bitcast<u32>(cardStorage[primOffset + 11u]),
                bitcast<u32>(cardStorage[primOffset + 2u]),
                1u);  // flag=1 indicates gradient type
        }
        default: { return vec4<u32>(0u); }
    }
}

fn ypaintIsGradientPrim(primType: u32) -> bool {
    switch (primType) {
        case SDF_LINEAR_GRADIENT_BOX: { return true; }
        case SDF_LINEAR_GRADIENT_CIRCLE: { return true; }
        case SDF_RADIAL_GRADIENT_CIRCLE: { return true; }
        default: { return false; }
    }
}

fn ypaintEvalGradientFillColor(primOffset: u32, p: vec2<f32>) -> vec4<f32> {
    // Layout: [0]=gridOffset, [1]=type, [2]=layer, [3+]=geometry
    // Read grid offset FIRST (u16,u16 packed) and convert to pixel offset
    let gridOffsetPacked = bitcast<u32>(cardStorage[primOffset + 0u]);
    let gridOffsetX = f32(gridOffsetPacked & 0xFFFFu);
    let gridOffsetY = f32(gridOffsetPacked >> 16u);
    let pixelOffset = vec2<f32>(gridOffsetX * grid.cellSize.x, gridOffsetY * grid.cellSize.y);
    let pAdj = p - pixelOffset;

    let primType = bitcast<u32>(cardStorage[primOffset + 1u]);
    switch (primType) {
        case SDF_LINEAR_GRADIENT_BOX: {
            let gStart = vec2<f32>(cardStorage[primOffset + 7u], cardStorage[primOffset + 8u]);
            let gEnd = vec2<f32>(cardStorage[primOffset + 9u], cardStorage[primOffset + 10u]);
            let gDir = gEnd - gStart;
            let gLen = length(gDir);
            let t = clamp(dot(pAdj - gStart, gDir) / (gLen * gLen), 0.0, 1.0);
            let c1 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 11u]));
            let c2 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 12u]));
            return mix(c1, c2, t);
        }
        case SDF_LINEAR_GRADIENT_CIRCLE: {
            let gStart = vec2<f32>(cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
            let gEnd = vec2<f32>(cardStorage[primOffset + 8u], cardStorage[primOffset + 9u]);
            let gDir = gEnd - gStart;
            let gLen = length(gDir);
            let t = clamp(dot(pAdj - gStart, gDir) / (gLen * gLen), 0.0, 1.0);
            let c1 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 10u]));
            let c2 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 11u]));
            return mix(c1, c2, t);
        }
        case SDF_RADIAL_GRADIENT_CIRCLE: {
            let gCenter = vec2<f32>(cardStorage[primOffset + 6u], cardStorage[primOffset + 7u]);
            let gRadius = cardStorage[primOffset + 8u];
            let t = clamp(length(pAdj - gCenter) / gRadius, 0.0, 1.0);
            let c1 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 9u]));
            let c2 = unpack4x8unorm(bitcast<u32>(cardStorage[primOffset + 10u]));
            return mix(c1, c2, t);
        }
        default: { return vec4<f32>(0.0); }
    }
}

fn ypaintPrimStrokeWidth(primOffset: u32) -> f32 {
    // Layout: [0]=gridOffset, [1]=type, [2]=layer, [3+]=geometry
    let primType = bitcast<u32>(cardStorage[primOffset + 1u]);
    switch (primType) {
        case SDF_CIRCLE: { return cardStorage[primOffset + 8u]; }
        case SDF_BOX: { return cardStorage[primOffset + 9u]; }
        case SDF_SEGMENT: { return cardStorage[primOffset + 9u]; }
        case SDF_TRIANGLE: { return cardStorage[primOffset + 11u]; }
        case SDF_BEZIER2: { return cardStorage[primOffset + 11u]; }
        case SDF_BEZIER3: { return cardStorage[primOffset + 13u]; }
        case SDF_ELLIPSE: { return cardStorage[primOffset + 9u]; }
        case SDF_ARC: { return cardStorage[primOffset + 11u]; }
        case SDF_ROUNDED_BOX: { return cardStorage[primOffset + 13u]; }
        case SDF_RHOMBUS: { return cardStorage[primOffset + 9u]; }
        case SDF_PENTAGON: { return cardStorage[primOffset + 8u]; }
        case SDF_HEXAGON: { return cardStorage[primOffset + 8u]; }
        case SDF_STAR: { return cardStorage[primOffset + 10u]; }
        case SDF_PIE: { return cardStorage[primOffset + 10u]; }
        case SDF_RING: { return cardStorage[primOffset + 11u]; }
        case SDF_HEART: { return cardStorage[primOffset + 8u]; }
        case SDF_CROSS: { return cardStorage[primOffset + 10u]; }
        case SDF_ROUNDED_X: { return cardStorage[primOffset + 9u]; }
        case SDF_CAPSULE: { return cardStorage[primOffset + 10u]; }
        case SDF_MOON: { return cardStorage[primOffset + 10u]; }
        case SDF_EGG: { return cardStorage[primOffset + 9u]; }
        case SDF_CHAMFER_BOX: { return cardStorage[primOffset + 10u]; }
        case SDF_ORIENTED_BOX: { return cardStorage[primOffset + 10u]; }
        case SDF_TRAPEZOID: { return cardStorage[primOffset + 10u]; }
        case SDF_PARALLELOGRAM: { return cardStorage[primOffset + 10u]; }
        case SDF_EQUILATERAL_TRIANGLE: { return cardStorage[primOffset + 8u]; }
        case SDF_ISOSCELES_TRIANGLE: { return cardStorage[primOffset + 9u]; }
        case SDF_UNEVEN_CAPSULE: { return cardStorage[primOffset + 10u]; }
        case SDF_OCTOGON: { return cardStorage[primOffset + 8u]; }
        case SDF_HEXAGRAM: { return cardStorage[primOffset + 8u]; }
        case SDF_PENTAGRAM: { return cardStorage[primOffset + 8u]; }
        case SDF_CUT_DISK: { return cardStorage[primOffset + 9u]; }
        case SDF_HORSESHOE: { return cardStorage[primOffset + 12u]; }
        case SDF_VESICA: { return cardStorage[primOffset + 9u]; }
        case SDF_ORIENTED_VESICA: { return cardStorage[primOffset + 10u]; }
        case SDF_ROUNDED_CROSS: { return cardStorage[primOffset + 8u]; }
        case SDF_PARABOLA: { return cardStorage[primOffset + 8u]; }
        case SDF_BLOBBY_CROSS: { return cardStorage[primOffset + 8u]; }
        case SDF_TUNNEL: { return cardStorage[primOffset + 9u]; }
        case SDF_STAIRS: { return cardStorage[primOffset + 10u]; }
        case SDF_QUADRATIC_CIRCLE: { return cardStorage[primOffset + 8u]; }
        case SDF_HYPERBOLA: { return cardStorage[primOffset + 9u]; }
        case SDF_COOL_S: { return cardStorage[primOffset + 8u]; }
        case SDF_CIRCLE_WAVE: { return cardStorage[primOffset + 9u]; }
        case SDF_COLOR_WHEEL: { return cardStorage[primOffset + 13u]; }
        case SDF_TEXT_GLYPH: { return cardStorage[primOffset + 10u]; }
        case SDF_ROTATED_GLYPH: { return cardStorage[primOffset + 13u]; }
        case SDF_SPHERE_3D: { return cardStorage[primOffset + 8u]; }
        case SDF_BOX_3D: { return cardStorage[primOffset + 10u]; }
        case SDF_TORUS_3D: { return cardStorage[primOffset + 9u]; }
        case SDF_CYLINDER_3D: { return cardStorage[primOffset + 9u]; }
        case SDF_VERTICAL_CAPSULE_3D: { return cardStorage[primOffset + 9u]; }
        case SDF_CAPPED_CONE_3D: { return cardStorage[primOffset + 10u]; }
        case SDF_OCTAHEDRON_3D: { return cardStorage[primOffset + 8u]; }
        case SDF_PYRAMID_3D: { return cardStorage[primOffset + 8u]; }
        case SDF_ELLIPSOID_3D: { return cardStorage[primOffset + 10u]; }
        case SDF_POLYGON: { return cardStorage[primOffset + 6u]; }
        case SDF_POLYGON_GROUP: { return cardStorage[primOffset + 7u]; }
        case SDF_LINEAR_GRADIENT_BOX: { return cardStorage[primOffset + 14u]; }
        case SDF_LINEAR_GRADIENT_CIRCLE: { return cardStorage[primOffset + 13u]; }
        case SDF_RADIAL_GRADIENT_CIRCLE: { return cardStorage[primOffset + 12u]; }
        default: { return 0.0; }
    }
}
