# ThorVG.cmake - Build ThorVG from source using CPM
#=============================================================================
# Builds ThorVG with software renderer and SVG/Lottie loaders.
# Creates thorvg_lib target for linking.
#=============================================================================

include_guard(GLOBAL)

# Download ThorVG from GitHub release
CPMAddPackage(
    NAME thorvg
    URL https://github.com/thorvg/thorvg/archive/refs/tags/v1.0.1.tar.gz
    DOWNLOAD_ONLY YES
)

if(thorvg_ADDED)
    # Generate config.h for ThorVG (required by the library)
    set(THORVG_CONFIG_H_CONTENT
"// ThorVG Configuration Header - Generated by CMake
#ifndef _TVG_CONFIG_H_
#define _TVG_CONFIG_H_

#define THORVG_VERSION_STRING \"1.0.1\"

// Engine Support - Software renderer for CPU-side rendering
#define THORVG_SW_RASTER_SUPPORT 1

// Loader Support
#define THORVG_SVG_LOADER_SUPPORT 1
#define THORVG_LOTTIE_LOADER_SUPPORT 1

#endif // _TVG_CONFIG_H_
")
    file(WRITE "${thorvg_SOURCE_DIR}/src/common/config.h" "${THORVG_CONFIG_H_CONTENT}")

    # Collect ThorVG source files
    file(GLOB THORVG_COMMON_SOURCES
        ${thorvg_SOURCE_DIR}/src/common/*.cpp
    )

    file(GLOB THORVG_RENDERER_SOURCES
        ${thorvg_SOURCE_DIR}/src/renderer/*.cpp
    )

    # Software engine for CPU rendering to buffer
    file(GLOB THORVG_SW_ENGINE_SOURCES
        ${thorvg_SOURCE_DIR}/src/renderer/sw_engine/*.cpp
    )

    file(GLOB THORVG_SVG_LOADER_SOURCES
        ${thorvg_SOURCE_DIR}/src/loaders/svg/*.cpp
    )

    file(GLOB THORVG_LOTTIE_LOADER_SOURCES
        ${thorvg_SOURCE_DIR}/src/loaders/lottie/*.cpp
    )

    file(GLOB THORVG_RAW_LOADER_SOURCES
        ${thorvg_SOURCE_DIR}/src/loaders/raw/*.cpp
    )

    set(THORVG_SOURCES
        ${THORVG_COMMON_SOURCES}
        ${THORVG_RENDERER_SOURCES}
        ${THORVG_SW_ENGINE_SOURCES}
        ${THORVG_SVG_LOADER_SOURCES}
        ${THORVG_LOTTIE_LOADER_SOURCES}
        ${THORVG_RAW_LOADER_SOURCES}
    )

    # Create thorvg library
    add_library(thorvg_lib STATIC ${THORVG_SOURCES})

    target_include_directories(thorvg_lib PUBLIC
        ${thorvg_SOURCE_DIR}/inc
    )

    target_include_directories(thorvg_lib PRIVATE
        ${thorvg_SOURCE_DIR}/src/common
        ${thorvg_SOURCE_DIR}/src/renderer
        ${thorvg_SOURCE_DIR}/src/renderer/sw_engine
        ${thorvg_SOURCE_DIR}/src/loaders/svg
        ${thorvg_SOURCE_DIR}/src/loaders/lottie
        ${thorvg_SOURCE_DIR}/src/loaders/raw
    )

    # Compile options - TVG_STATIC must be PUBLIC so consumers also get it
    # (prevents __declspec(dllimport) in thorvg.h on Windows)
    target_compile_definitions(thorvg_lib PUBLIC
        TVG_STATIC
    )
    target_compile_definitions(thorvg_lib PRIVATE
        $<$<PLATFORM_ID:Windows>:NOMINMAX>
        $<$<PLATFORM_ID:Windows>:WIN32_LEAN_AND_MEAN>
    )

    set_target_properties(thorvg_lib PROPERTIES
        POSITION_INDEPENDENT_CODE ON
        CXX_STANDARD 17
        CXX_STANDARD_REQUIRED ON
    )

    # Suppress warnings in third-party code
    if(MSVC)
        target_compile_options(thorvg_lib PRIVATE /w)
    else()
        target_compile_options(thorvg_lib PRIVATE -w)
    endif()

    message(STATUS "ThorVG: Built from source v1.0")
endif()
