# Shared configuration for all platforms
# Include this before platform-specific target files

# Auto-generate MSDF CDB fonts if not present (must run before incbin)
include(${YETTY_ROOT}/build-tools/cmake/prepare-assets.cmake)

# Common libraries needed by all platforms
include(${YETTY_ROOT}/build-tools/cmake/incbin.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/args.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/lz4.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/libuv.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/glm.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/stb.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/yaml-cpp.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/spdlog.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/ytrace.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/msgpack.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/webgpu.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/vterm.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/zlib.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/libpng.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/msdfgen.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/cdb.cmake)
include(${YETTY_ROOT}/build-tools/cmake/thorvg.cmake)
include(${YETTY_ROOT}/build-tools/cmake/TreeSitter.cmake)
include(${YETTY_ROOT}/build-tools/cmake/Dav1d.cmake)
include(${YETTY_ROOT}/build-tools/cmake/openh264.cmake)
include(${YETTY_ROOT}/build-tools/cmake/minimp4.cmake)
include(${YETTY_ROOT}/build-tools/cmake/libs/wasm3.cmake)

# Common include directories
set(YETTY_INCLUDES
    ${YETTY_ROOT}/src
    ${YETTY_ROOT}/include
)

# Common compile definitions
set(YETTY_DEFINITIONS
    CMAKE_SOURCE_DIR="${YETTY_ROOT}"
)

# Common libraries to link
set(YETTY_LIBS
    webgpu
    glm::glm
    stb
    yaml-cpp
    vterm
    msgpack-cxx
    msdfgen::msdfgen-core
    msdfgen::msdfgen-ext
    cdb-wrapper
    yetty_base
    yetty_font
    yetty_yecho
    yetty_ydraw
    yetty_ypaint
    yetty_diagram
    ygrid
    yetty_cards
    yetty_yast
    yetty_telnet
    msdf-wgsl
    args
)

#-----------------------------------------------------------------------------
# yetty_embed_assets(TARGET)
#
# Embeds shaders, fonts, and CDB files into the target binary.
# Call this AFTER creating the target with add_executable/add_library.
# WebAssembly: provides empty stubs (uses --preload-file instead)
#-----------------------------------------------------------------------------
function(yetty_embed_assets TARGET)
    # Embed logo
    incbin_add_resources(${TARGET}
        Logo "${YETTY_ROOT}/docs/logo.jpeg"
    )

    # Embed shaders from source
    incbin_add_directory(${TARGET} "shaders" "${YETTY_ROOT}/src/yetty/shaders" "*.wgsl")

    # Embed fonts from source (brotli compressed)
    incbin_add_directory(${TARGET} "fonts" "${YETTY_ROOT}/assets" "*.ttf" TRUE)

    # Embed MSDF CDB font databases (brotli compressed)
    # CDB files are generated by prepare-assets.cmake at configure time
    incbin_add_directory(${TARGET} "msdf-fonts" "${CMAKE_BINARY_DIR}/assets/msdf-fonts" "*.cdb" TRUE)

    # Make manifest headers available
    target_include_directories(${TARGET} PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
endfunction()
