#include <yetty/incbin-assets.h>
#include <ytrace/ytrace.hpp>

#include <brotli/decode.h>

#include <cstring>
#include <fstream>
#include <unordered_map>
#include <vector>

// Build version for extraction marker
#ifndef YETTY_BUILD_VERSION
#define YETTY_BUILD_VERSION "dev"
#endif

// Embedded resource declarations (generated by incbin)
// Format: INCBIN(Name, "path") generates gNameData[], gNameSize, gNameEnd
extern "C" {
    // Logo (always embedded)
    extern const unsigned char gLogoData[];
    extern const unsigned int gLogoSize;
}

// Include generated asset manifests
// These are generated by incbin_add_directory() in CMake
// HAS_*_MANIFEST macros are defined via target_compile_definitions
#ifdef HAS_SHADERS_MANIFEST
#include "yetty_shaders_manifest.h"
#endif

#ifdef HAS_FONTS_MANIFEST
#include "yetty_fonts_manifest.h"
#endif

#ifdef HAS_FONTS_CDB_MANIFEST
#include "yetty_fonts-cdb_manifest.h"  // Note: file has hyphen, but function uses underscore
#endif

namespace yetty {

struct AssetEntry {
    const uint8_t* data;
    size_t size;
    bool compressed;  // true if brotli compressed
};

class IncbinAssetsImpl : public IncbinAssets {
public:
    IncbinAssetsImpl() {
        // Register all embedded assets
        // Name format matches the extraction path
        registerAsset("logo.jpeg", gLogoData, gLogoSize, false);

        // Register shaders from generated manifest
#ifdef HAS_SHADERS_MANIFEST
        register_shaders_assets([this](const char* name, const uint8_t* data, size_t size, bool compressed) {
            registerAsset(name, data, size, compressed);
        });
        yinfo("Registered shader assets from manifest");
#endif

        // Register fonts from generated manifest
#ifdef HAS_FONTS_MANIFEST
        register_fonts_assets([this](const char* name, const uint8_t* data, size_t size, bool compressed) {
            registerAsset(name, data, size, compressed);
        });
        yinfo("Registered font assets from manifest");
#endif

        // Register MSDF CDB font databases from generated manifest
#ifdef HAS_FONTS_CDB_MANIFEST
        register_fonts_cdb_assets([this](const char* name, const uint8_t* data, size_t size, bool compressed) {
            registerAsset(name, data, size, compressed);
        });
        yinfo("Registered MSDF CDB font assets from manifest");
#endif

        yinfo("IncbinAssets: {} embedded assets available", _assets.size());
    }

    std::span<const uint8_t> get(std::string_view name) const override {
        auto it = _assets.find(std::string(name));
        if (it == _assets.end()) {
            return {};
        }
        return {it->second.data, it->second.size};
    }

    std::string_view getString(std::string_view name) const override {
        auto data = get(name);
        if (data.empty()) {
            return {};
        }
        return {reinterpret_cast<const char*>(data.data()), data.size()};
    }

    bool has(std::string_view name) const override {
        return _assets.contains(std::string(name));
    }

    std::vector<std::string> list() const override {
        std::vector<std::string> names;
        names.reserve(_assets.size());
        for (const auto& [name, _] : _assets) {
            names.push_back(name);
        }
        return names;
    }

    Result<void> extractTo(const std::filesystem::path& dir) const override {
        namespace fs = std::filesystem;

        yinfo("Extracting {} embedded assets to {}", _assets.size(), dir.string());

        for (const auto& [name, entry] : _assets) {
            auto path = dir / name;

            // Create parent directories
            auto parentDir = path.parent_path();
            if (!parentDir.empty() && !fs::exists(parentDir)) {
                std::error_code ec;
                fs::create_directories(parentDir, ec);
                if (ec) {
                    return Err<void>("Failed to create directory: " + parentDir.string());
                }
            }

            // Decompress if needed
            const uint8_t* writeData = entry.data;
            size_t writeSize = entry.size;
            std::vector<uint8_t> decompressed;

            if (entry.compressed) {
                auto result = decompressBrotli(entry.data, entry.size);
                if (!result) {
                    return Err<void>("Failed to decompress " + name);
                }
                decompressed = std::move(result.value());
                writeData = decompressed.data();
                writeSize = decompressed.size();
                ydebug("Decompressed: {} ({} -> {} bytes)", name, entry.size, writeSize);
            }

            // Write file
            std::ofstream file(path, std::ios::binary);
            if (!file) {
                return Err<void>("Failed to open file for writing: " + path.string());
            }
            file.write(reinterpret_cast<const char*>(writeData), writeSize);
            if (!file) {
                return Err<void>("Failed to write file: " + path.string());
            }

            if (!entry.compressed) {
                ydebug("Extracted: {} ({} bytes)", name, writeSize);
            }
        }

        // Write extraction marker
        auto marker = getExtractionMarker(dir);
        fs::create_directories(marker.parent_path());
        std::ofstream markerFile(marker);
        if (markerFile) {
            markerFile << YETTY_BUILD_VERSION;
        }

        yinfo("Asset extraction complete");
        return Ok();
    }

    Result<void> extractAsset(std::string_view name,
                               const std::filesystem::path& path) const override {
        auto data = get(name);
        if (data.empty()) {
            return Err<void>("Asset not found: " + std::string(name));
        }

        // Create parent directories
        auto parentDir = path.parent_path();
        if (!parentDir.empty() && !std::filesystem::exists(parentDir)) {
            std::error_code ec;
            std::filesystem::create_directories(parentDir, ec);
            if (ec) {
                return Err<void>("Failed to create directory: " + parentDir.string());
            }
        }

        std::ofstream file(path, std::ios::binary);
        if (!file) {
            return Err<void>("Failed to open file: " + path.string());
        }
        file.write(reinterpret_cast<const char*>(data.data()), data.size());
        return Ok();
    }

private:
    void registerAsset(const std::string& name, const uint8_t* data, size_t size, bool compressed) {
        _assets[name] = {data, size, compressed};
    }

    Result<std::vector<uint8_t>> decompressBrotli(const uint8_t* data, size_t size) const {
        // Get decompressed size (brotli doesn't store it, so we need to decompress)
        size_t decodedSize = size * 10;  // Initial estimate
        std::vector<uint8_t> output(decodedSize);

        BrotliDecoderResult result;
        do {
            decodedSize = output.size();
            result = BrotliDecoderDecompress(size, data, &decodedSize, output.data());
            if (result == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT) {
                output.resize(output.size() * 2);
            }
        } while (result == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT);

        if (result != BROTLI_DECODER_RESULT_SUCCESS) {
            return Err<std::vector<uint8_t>>("Brotli decompression failed");
        }

        output.resize(decodedSize);
        return Ok(std::move(output));
    }

    std::unordered_map<std::string, AssetEntry> _assets;
};

// Static helper implementations
std::filesystem::path IncbinAssets::getExtractionMarker(const std::filesystem::path& cacheDir) {
    return cacheDir / ".yetty-assets" / "version";
}

bool IncbinAssets::needsExtraction(const std::filesystem::path& cacheDir) {
    auto marker = getExtractionMarker(cacheDir);
    if (!std::filesystem::exists(marker)) {
        return true;
    }

    // Check version
    std::ifstream file(marker);
    std::string version;
    std::getline(file, version);
    return version != YETTY_BUILD_VERSION;
}

// Singleton factory
Result<IncbinAssets::Ptr> IncbinAssets::createImpl() {
    return Ok(std::make_shared<IncbinAssetsImpl>());
}

}  // namespace yetty
