#include "grammars.h"

#include <cstring>
#include <unordered_map>

// Tree-sitter language functions (from each grammar's parser.c)
extern "C" {
const TSLanguage* tree_sitter_c(void);
const TSLanguage* tree_sitter_cpp(void);
const TSLanguage* tree_sitter_python(void);
const TSLanguage* tree_sitter_javascript(void);
const TSLanguage* tree_sitter_typescript(void);
const TSLanguage* tree_sitter_rust(void);
const TSLanguage* tree_sitter_go(void);
const TSLanguage* tree_sitter_java(void);
const TSLanguage* tree_sitter_bash(void);
const TSLanguage* tree_sitter_json(void);
const TSLanguage* tree_sitter_yaml(void);
const TSLanguage* tree_sitter_toml(void);
}

// Embedded highlight queries (generated by CMake — see embed_queries.cmake)
#include "ts_queries_generated.h"

namespace ycat::ts {

static const GrammarInfo s_grammars[] = {
    {"c",          tree_sitter_c,          TS_QUERY_c,          sizeof(TS_QUERY_c) - 1},
    {"cpp",        tree_sitter_cpp,        TS_QUERY_cpp,        sizeof(TS_QUERY_cpp) - 1},
    {"python",     tree_sitter_python,     TS_QUERY_python,     sizeof(TS_QUERY_python) - 1},
    {"javascript", tree_sitter_javascript, TS_QUERY_javascript, sizeof(TS_QUERY_javascript) - 1},
    {"typescript", tree_sitter_typescript, TS_QUERY_typescript, sizeof(TS_QUERY_typescript) - 1},
    {"rust",       tree_sitter_rust,       TS_QUERY_rust,       sizeof(TS_QUERY_rust) - 1},
    {"go",         tree_sitter_go,         TS_QUERY_go,         sizeof(TS_QUERY_go) - 1},
    {"java",       tree_sitter_java,       TS_QUERY_java,       sizeof(TS_QUERY_java) - 1},
    {"bash",       tree_sitter_bash,       TS_QUERY_bash,       sizeof(TS_QUERY_bash) - 1},
    {"json",       tree_sitter_json,       TS_QUERY_json,       sizeof(TS_QUERY_json) - 1},
    {"yaml",       tree_sitter_yaml,       TS_QUERY_yaml,       sizeof(TS_QUERY_yaml) - 1},
    {"toml",       tree_sitter_toml,       TS_QUERY_toml,       sizeof(TS_QUERY_toml) - 1},
};

static const std::unordered_map<std::string_view, const GrammarInfo*>& grammarMap() {
    static std::unordered_map<std::string_view, const GrammarInfo*> map;
    if (map.empty()) {
        for (const auto& g : s_grammars) {
            map[g.name] = &g;
        }
    }
    return map;
}

const GrammarInfo* getGrammar(std::string_view name) {
    auto& map = grammarMap();
    auto it = map.find(name);
    return it != map.end() ? it->second : nullptr;
}

} // namespace ycat::ts
