#!/usr/bin/env python3
"""
Generate glyph registry header from shader files.

Scans shader directory for files like 0x0000-spinner.wgsl and generates
a C++ header with embedded name→codepoint mappings.

Usage: python gen-glyph-registry.py <shader_dir> <output_header>
"""

import sys
import re
from pathlib import Path

SHADER_GLYPH_BASE = 0x101000

def parse_shader_filename(filename: str) -> tuple[int, str] | None:
    """Parse '0xNNNN-name.wgsl' -> (offset, name)"""
    match = re.match(r'^0x([0-9a-fA-F]+)-(.+)\.wgsl$', filename)
    if match:
        offset = int(match.group(1), 16)
        name = match.group(2)
        return (offset, name)
    return None

def scan_glyphs(shader_dir: Path) -> list[tuple[str, int]]:
    """Scan directory for glyph shaders, return [(name, codepoint), ...]"""
    glyphs_dir = shader_dir / "glyphs"
    if not glyphs_dir.exists():
        print(f"Warning: {glyphs_dir} does not exist", file=sys.stderr)
        return []
    
    glyphs = []
    for path in sorted(glyphs_dir.glob("*.wgsl")):
        result = parse_shader_filename(path.name)
        if result:
            offset, name = result
            codepoint = SHADER_GLYPH_BASE + offset
            glyphs.append((name, codepoint))
    
    return sorted(glyphs, key=lambda x: x[0])  # Sort by name

def generate_header(glyphs: list[tuple[str, int]]) -> str:
    """Generate C++ header content."""
    lines = [
        "// Auto-generated by gen-glyph-registry.py - DO NOT EDIT",
        "#pragma once",
        "",
        "#include <string_view>",
        "#include <cstdint>",
        "#include <array>",
        "",
        "namespace yetty {",
        "namespace generated {",
        "",
        f"inline constexpr uint32_t SHADER_GLYPH_BASE = 0x{SHADER_GLYPH_BASE:06X};",
        "",
        "struct GlyphEntry {",
        "    std::string_view name;",
        "    uint32_t codepoint;",
        "};",
        "",
        f"inline constexpr std::array<GlyphEntry, {len(glyphs)}> GLYPHS = {{{{",
    ]
    
    for name, codepoint in glyphs:
        lines.append(f'    {{"{name}", 0x{codepoint:06X}}},')
    
    lines.extend([
        "}};",
        "",
        "} // namespace generated",
        "} // namespace yetty",
    ])
    
    return "\n".join(lines)

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <shader_dir> <output_header>", file=sys.stderr)
        sys.exit(1)
    
    shader_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    
    glyphs = scan_glyphs(shader_dir)
    
    if not glyphs:
        print(f"Warning: No glyphs found in {shader_dir}/glyphs/", file=sys.stderr)
    
    header = generate_header(glyphs)
    
    # Only write if changed (avoid unnecessary rebuilds)
    if output_path.exists():
        existing = output_path.read_text()
        if existing == header:
            print(f"Glyph registry unchanged ({len(glyphs)} glyphs)")
            return
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)
    print(f"Generated {output_path} with {len(glyphs)} glyphs")

if __name__ == "__main__":
    main()
